# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myauth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmyauth.proto\x12\x06myauth\"\x1b\n\x0b\x41uthRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1d\n\tAuthReply\x12\x10\n\x08\x63\x61n_view\x18\x01 \x01(\x08\x32\x44\n\x0b\x41uthChecker\x12\x35\n\tCheckAuth\x12\x13.myauth.AuthRequest\x1a\x11.myauth.AuthReply\"\x00\x42:\n\x17io.grpc.examples.myauthB\x0bMyAuthProtoP\x01Z\x10myproject/myauthb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myauth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.grpc.examples.myauthB\013MyAuthProtoP\001Z\020myproject/myauth'
  _AUTHREQUEST._serialized_start=24
  _AUTHREQUEST._serialized_end=51
  _AUTHREPLY._serialized_start=53
  _AUTHREPLY._serialized_end=82
  _AUTHCHECKER._serialized_start=84
  _AUTHCHECKER._serialized_end=152
# @@protoc_insertion_point(module_scope)
